publish_to: https://pub.dev

name: enum_as_string
version: 1.0.0+3

description: A simple utility library for enum-to-string and string-to-enum conversions. 

homepage: https://github.com/wordcollector/enum_as_string
repository: https://github.com/wordcollector/enum_as_string
issue_tracker: https://github.com/wordcollector/enum_as_string/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.19.4
  words: ^0.0.2+1
